apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: selfservice-api
    app.kubernetes.io/component: api-gateway
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: selfservice-api
    app.kubernetes.io/component: api-gateway
