apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-engine
  labels:
    app.kubernetes.io/name: selfservice-api
    app.kubernetes.io/component: crucible-engine
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.engine.port | default 8081 }}
      targetPort: callback
      protocol: TCP
      name: callback
  selector:
    app.kubernetes.io/name: selfservice-api
    app.kubernetes.io/component: crucible-engine
