{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app.kubernetes.io/name: selfservice-api
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.hostname }}`) && (PathPrefix(`/api/`) || PathPrefix(`/auth/`) || PathPrefix(`/healthz`) || PathPrefix(`/readyz`))
      kind: Rule
      services:
        - name: {{ .Release.Name }}-api
          port: {{ .Values.api.port }}
    - match: Host(`{{ .Values.ingress.hostname }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-api
          port: {{ .Values.api.port }}
{{- end }}
