apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: selfservice-api
    app.kubernetes.io/component: api-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app.kubernetes.io/name: selfservice-api
    app.kubernetes.io/component: provision-worker
