BEGIN;

DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS pod_vms;
DROP TABLE IF EXISTS pods;
DROP TABLE IF EXISTS template_access;
DROP TABLE IF EXISTS templates;
DROP TABLE IF EXISTS users;

COMMIT;
